### ISSUE TITLE
Stylus files

### ISSUE THREAD

**Issue by Yumshot** [code-biscuits/html-biscuits#3]
Not sure if it'd be considered an issue or not , however styl files does not capture the class/id title in a chunk but rather captures by line , 

<img src="https://i.imgur.com/1alaQJo.png"
     alt="Error Image" />

**Comment by cmgriffing** [comment]
Sorry, this is a bug of the JS/TS biscuits. JS/TS biscuits will be scoped to just the relevant file types and that should fix it.

The stylus stuff might have to be its own biscuit plugin, but I will try to see if it can be part of the css biscuit plugin I am planning soon.

Just to verify that my assumption is correct, please change the color of each plugin to be different and then we can be certain.
